dist: trusty
language: node_js

node_js:
  - "10"

addons:
  sonarcloud:
    organization: "ojousima"
    token:
      secure: $SONAR_TOKEN
      
install:
  - npm install

script:
  - npm run test && npm run lint && sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
